package com.amitchorasiya.github.copilot.toolbox.intellij.parity

import com.intellij.openapi.fileEditor.FileEditorManager
import com.intellij.openapi.project.Project
import com.intellij.openapi.ui.Messages
import com.intellij.openapi.vfs.LocalFileSystem
import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path

private val STUB = """---
name: my-skill
description: Describe when this skill applies (project-specific workflow).
---

# My skill

## When to use

- 

## Steps

1. 

<!--
  Stub generated by Github Copilot ToolBox.
  Structure inspired by community SKILL.md conventions (e.g. everything-claude-code, MIT).
-->
"""

/** Mirrors [packages/cloude-code-toolbox/src/commands/skillStubCommand.ts]. */
object SkillStubIntellij {

    fun run(project: Project) {
        val base = project.basePath ?: run {
            Messages.showErrorDialog(project, "Open a workspace folder first.", "Github Copilot ToolBox")
            return
        }
        val name = Messages.showInputDialog(
            project,
            "Skill folder name (under .github/skills):",
            "Create SKILL.md stub",
            Messages.getQuestionIcon(),
        )?.trim().orEmpty()
        if (name.isEmpty()) return
        if (!Regex("^[a-z0-9-]{2,64}$", RegexOption.IGNORE_CASE).matches(name)) {
            Messages.showErrorDialog(project, "Use 2–64 chars: letters, numbers, hyphen.", "Github Copilot ToolBox")
            return
        }
        val root = Path.of(base)
        val dir = root.resolve(".github").resolve("skills").resolve(name)
        val file = dir.resolve("SKILL.md")
        if (Files.exists(file)) {
            Messages.showErrorDialog(project, "SKILL.md already exists at that path.", "Github Copilot ToolBox")
            return
        }
        Files.createDirectories(dir)
        Files.writeString(file, STUB, StandardCharsets.UTF_8)
        val vf = LocalFileSystem.getInstance().refreshAndFindFileByIoFile(file.toFile()) ?: return
        FileEditorManager.getInstance(project).openFile(vf, true)
        Messages.showInfoMessage(project, "Created .github/skills/$name/SKILL.md", "Github Copilot ToolBox")
    }
}
