import * as vscode from "vscode";
import * as mcpPaths from "../mcpPaths";

const STUB = `---
name: my-skill
description: Describe when this skill applies (project-specific workflow).
---

# My skill

## When to use

- 

## Steps

1. 

<!--
  Stub generated by GitHub Copilot Toolbox.
  Structure inspired by community SKILL.md conventions (e.g. everything-claude-code, MIT).
-->
`;

/** Create a minimal SKILL.md stub under .github/skills/<name>/ or user-chosen folder. */
export async function createSkillStubCommand(): Promise<void> {
  const folder = mcpPaths.getPrimaryWorkspaceFolder();
  if (!folder) {
    vscode.window.showErrorMessage("Open a workspace folder first.");
    return;
  }
  const name =
    (await vscode.window.showInputBox({
      title: "Skill folder name (under .github/skills)",
      placeHolder: "e.g. api-design",
      validateInput: (v) =>
        /^[a-z0-9-]{2,64}$/i.test((v ?? "").trim()) ? null : "Use 2–64 chars: letters, numbers, hyphen.",
    }))?.trim() ?? "";
  if (!name) {
    return;
  }
  const dir = vscode.Uri.joinPath(folder.uri, ".github", "skills", name);
  const file = vscode.Uri.joinPath(dir, "SKILL.md");
  try {
    await vscode.workspace.fs.stat(file);
    vscode.window.showErrorMessage("SKILL.md already exists at that path.");
    return;
  } catch {
    /* missing */
  }
  await vscode.workspace.fs.createDirectory(dir);
  const enc = new TextEncoder();
  await vscode.workspace.fs.writeFile(file, enc.encode(STUB));
  const doc = await vscode.workspace.openTextDocument(file);
  await vscode.window.showTextDocument(doc);
  vscode.window.showInformationMessage(`Created ${vscode.workspace.asRelativePath(file, false)}`);
}
