package com.amitchorasiya.github.copilot.toolbox.intellij.hub

/**
 * Every `GitHubCopilotToolBox.*` command id from the VS Code extension `package.json` `contributes.commands`,
 * plus programmatic / hub-only ids so `runCommand` from the JCEF hub resolves.
 */
object VsCodeHubCommandIds {

    val ALL: List<String> = listOf(
        "GitHubCopilotToolBox.openWorkspaceMcp",
        "GitHubCopilotToolBox.openUserMcp",
        "GitHubCopilotToolBox.mcpListServers",
        "GitHubCopilotToolBox.mcpBrowseRegistry",
        "GitHubCopilotToolBox.mcpAddServer",
        "GitHubCopilotToolBox.portCursorMcp",
        "GitHubCopilotToolBox.manualPortCursorMcpWithoutNpx",
        "GitHubCopilotToolBox.syncCursorRules",
        "GitHubCopilotToolBox.cursorRulesToCopilotWithoutNpx",
        "GitHubCopilotToolBox.initMemoryBank",
        "GitHubCopilotToolBox.memoryBankWithoutNpx",
        "GitHubCopilotToolBox.workspaceSetupWizard",
        "GitHubCopilotToolBox.openCopilotChat",
        "GitHubCopilotToolBox.toggleMcpDiscovery",
        "GitHubCopilotToolBox.refreshMcpView",
        "GitHubCopilotToolBox.refreshWorkspaceView",
        "GitHubCopilotToolBox.openInstructionsPicker",
        "GitHubCopilotToolBox.appendCursorrules",
        "GitHubCopilotToolBox.mergeClaudeMdIntoCopilotInstructions",
        "GitHubCopilotToolBox.createCursorrulesTemplate",
        "GitHubCopilotToolBox.openCursorCopilotReference",
        "GitHubCopilotToolBox.openInlineChatCursorStyle",
        "GitHubCopilotToolBox.openComposerHub",
        "GitHubCopilotToolBox.openSessionNotepad",
        "GitHubCopilotToolBox.copySessionNotepad",
        "GitHubCopilotToolBox.openCopilotBillingDocs",
        "GitHubCopilotToolBox.openEnvSyncChecklist",
        "GitHubCopilotToolBox.translateContextSelection",
        "GitHubCopilotToolBox.buildContextPack",
        "GitHubCopilotToolBox.runThinkingMachinePriming",
        "GitHubCopilotToolBox.showMcpSkillsAwareness",
        "GitHubCopilotToolBox.showIntelligenceReadiness",
        "GitHubCopilotToolBox.openIntelligenceSettings",
        "GitHubCopilotToolBox.openThinkingMachineModeSettings",
        "GitHubCopilotToolBox.openIntelligenceToolboxRepos",
        "GitHubCopilotToolBox.openIntelligenceRepoMcpPort",
        "GitHubCopilotToolBox.openIntelligenceRepoMemoryBank",
        "GitHubCopilotToolBox.openIntelligenceRepoRulesConverter",
        "GitHubCopilotToolBox.migrateSkillsCursorToAgents",
        "GitHubCopilotToolBox.migrateSkillsClaudeToAgents",
        "GitHubCopilotToolBox.portClaudeProjectMcp",
        "GitHubCopilotToolBox.revealSkillFoldersWithoutNpx",
        "GitHubCopilotToolBox.copilotToolboxConfigScan",
        "GitHubCopilotToolBox.appendNotepadToMemoryBank",
        "GitHubCopilotToolBox.createSkillStub",
        "GitHubCopilotToolBox.verificationChecklist",
        "GitHubCopilotToolBox.applyBundledMcpRecipe",
        "GitHubCopilotToolBox.runFirstWorkspaceTestTask",
        "GitHubCopilotToolBox.runOneClickSetup",
        "GitHubCopilotToolBox.openOneClickSetupSettings",
        "GitHubCopilotToolBox.enableClaudeCopilotChatAgent",
        "GitHubCopilotToolBox.showClaudeCopilotAgentPrerequisites",
        "GitHubCopilotToolBox.enableCopilotCli",
        "GitHubCopilotToolBox.registerAwesomeCopilotMarketplace",
        "GitHubCopilotToolBox.copyAwesomeCopilotChatPrompt",
        "GitHubCopilotToolBox.openCopilotCliChatSession",
        "GitHubCopilotToolBox.openKitTarget",
    )
}
